package config

import (
	"strings"
	"testing"
)

func TestDefault(t *testing.T) {
	cfg := Default()
	if cfg.Host != "127.0.0.1" {
		t.Errorf("default host = %q, want 127.0.0.1", cfg.Host)
	}
	if cfg.Port != 3306 {
		t.Errorf("default port = %d, want 3306", cfg.Port)
	}
	if cfg.BatchSize != 500 {
		t.Errorf("default batch_size = %d, want 500", cfg.BatchSize)
	}
	if cfg.SleepMs != 100 {
		t.Errorf("default sleep_ms = %d, want 100", cfg.SleepMs)
	}
	if cfg.MaxLagSec != 1 {
		t.Errorf("default max_lag_sec = %d, want 1", cfg.MaxLagSec)
	}
}

func TestValidate_Required(t *testing.T) {
	cfg := Default()
	err := cfg.Validate()
	if err == nil {
		t.Fatal("expected error for missing required fields")
	}
	if !strings.Contains(err.Error(), "user") {
		t.Errorf("expected user required error, got: %v", err)
	}
}

func TestValidate_AllFields(t *testing.T) {
	cfg := validConfig()
	if err := cfg.Validate(); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestValidate_BatchSize(t *testing.T) {
	cfg := validConfig()

	cfg.BatchSize = 50
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for batch_size < 100")
	}

	cfg.BatchSize = 6000
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for batch_size > 5000")
	}

	cfg.BatchSize = 500
	if err := cfg.Validate(); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestValidate_SleepMs(t *testing.T) {
	cfg := validConfig()

	cfg.SleepMs = -1
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for negative sleep_ms")
	}

	cfg.SleepMs = 10001
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for sleep_ms > 10000")
	}
}

func TestValidate_MaxLagSec(t *testing.T) {
	cfg := validConfig()

	cfg.MaxLagSec = 0
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for max_lag_sec = 0")
	}

	cfg.MaxLagSec = 61
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for max_lag_sec > 60")
	}
}

func TestValidate_NiceRatio(t *testing.T) {
	cfg := validConfig()

	cfg.NiceRatio = -0.1
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for negative nice_ratio")
	}

	cfg.NiceRatio = 5.1
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for nice_ratio > 5.0")
	}

	cfg.NiceRatio = 1.5
	if err := cfg.Validate(); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestGetTaskID_Custom(t *testing.T) {
	cfg := validConfig()
	cfg.TaskID = "my-task"
	if got := cfg.GetTaskID(); got != "my-task" {
		t.Errorf("GetTaskID = %q, want my-task", got)
	}
}

func TestGetTaskID_AutoGenerated(t *testing.T) {
	cfg := validConfig()
	cfg.TaskID = ""
	id := cfg.GetTaskID()
	if !strings.HasPrefix(id, "users_") {
		t.Errorf("auto-generated task ID should start with table name: %q", id)
	}
	if len(strings.Split(id, "_")) < 3 {
		t.Errorf("auto-generated task ID should have format table_hash_ts: %q", id)
	}
}

func TestGetTaskID_Deterministic(t *testing.T) {
	cfg := validConfig()
	cfg.TaskID = ""
	id1 := cfg.GetTaskID()
	id2 := cfg.GetTaskID()
	// Hash part should be the same, timestamp may differ
	hash1 := strings.Split(id1, "_")[1]
	hash2 := strings.Split(id2, "_")[1]
	if hash1 != hash2 {
		t.Errorf("hash part should be deterministic: %q vs %q", hash1, hash2)
	}
}

func TestDSN(t *testing.T) {
	cfg := validConfig()
	dsn := cfg.DSN()
	if !strings.Contains(dsn, "root:secret@tcp(10.0.0.1:3307)/testdb") {
		t.Errorf("DSN = %q", dsn)
	}
	if !strings.Contains(dsn, "parseTime=true") {
		t.Error("DSN should contain parseTime=true")
	}
}

func TestAnnotate(t *testing.T) {
	cfg := validConfig()
	cfg.TaskID = "test-task"
	annotated := cfg.Annotate("SELECT 1")
	if !strings.Contains(annotated, "/* mydml:task=test-task */") {
		t.Errorf("Annotate = %q, missing comment", annotated)
	}
	if !strings.Contains(annotated, "SELECT 1") {
		t.Errorf("Annotate = %q, missing original SQL", annotated)
	}
}

func validConfig() *Config {
	return &Config{
		Host:      "10.0.0.1",
		Port:      3307,
		User:      "root",
		Password:  "secret",
		Database:  "testdb",
		Table:     "users",
		Where:     "created_at < '2024-01-01'",
		BatchSize: 500,
		SleepMs:   100,
		MaxLagSec: 1,
		NiceRatio: 0,
	}
}
